### PR TITLE
refresh codegen to pick up secfiles DSL fix

### LINKED ISSUE #81: secondaryFiles with pattern cannot be parsed when given in workflow inputs
When parsing packed cwl which has the `secondaryFiles` given in the workflow inputs raises the error below:
```
org.w3id.cwl.cwl1_2.utils.ValidationException: Failed to match union type
  Trying 'RecordField'
    the `class` field is not valid because:
      Expected one of [Ljava.lang.String;@7c28c1
  Trying 'RecordField'
    the `class` field is not valid because:
      Expected one of [Ljava.lang.String;@75b3673
    the `inputs` field is not valid because:
      Failed to match union type
        Expected object with Java type of java.util.List but got java.util.LinkedHashMap
        Trying 'RecordField'
          the `secondaryFiles` field is not valid because:
            Missing 'pattern' in secondaryFiles specification entry.
    the `expression` field is not valid because:
      Expected a string.
```

where the `secondaryFiles` is given in the standard schema:
```
                        "secondaryFiles": [
                            {
                                "pattern": "^.bai",
                                "required": true
                            }
                        ], 
```

However, reformating it as a list of strings would work: 
```
                         "secondaryFiles": [ "^.bai" ], 
 ```
 
The issue might result from https://github.com/common-workflow-lab/cwljava/blob/fd2d2bb0652e9d57ecee8c380157cc0f3186d636/src/main/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesDslLoader.java#L38-L44

where the `pattern` and `required` entries are removed and the source doc is modified, so when iterating candidate loaders in unionloader.java the latter could not find those entries. 
For example, when testing I noticed that the loader of CommandInputParameter processed the inputs first and removed the secondaryFiles `pattern` and `required`, but later when the workflow input parameter loader tried to parse the doc it could only find an empty map.

The secondaryFiles as tool inputs seem to be working. So as the ones in the short format in both workflow and tool level.

### PR DESCRIPTION
**Pull request by mr-c**
Pick up the fix from https://github.com/common-workflow-language/schema_salad/pull/526
Fixes #81

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks you @YuxinShi0423 for the detailed report and example code; this made it quite east to fix!

File: src/main/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesDslLoader.java [hunk 1]
```diff
@@ -34,7 +34,8 @@ public T load(
 	  }
 	  r.add(entry);
 	} else if (d instanceof Map) {
-	  Map<String, Object> dMap = (Map<String, Object>) d;
+	  @SuppressWarnings("unchecked")
+	  Map<String, Object> dMap = new HashMap<String, Object>((Map<String, Object>) d);
```
Comment (mr-c) [inline src/main/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesDslLoader.java:38]: The actual fix part 1

File: src/main/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesDslLoader.java [hunk 2]
```diff
@@ -53,7 +54,8 @@ public T load(
       }
     } else if (doc instanceof Map) {
       Map<String, Object> entry = new HashMap<String, Object>();
-      Map<String, Object> dMap = (Map<String, Object>) doc;
+      @SuppressWarnings("unchecked")
+      Map<String, Object> dMap = new HashMap<String, Object>((Map<String, Object>) doc);
```
Comment (mr-c) [inline src/main/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesDslLoader.java:58]: The actual fix part 2

File: src/test/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesTest.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    SecondaryFileSchema sec_files1 = sec_files_l1.get(0);
+    Assert.assertEquals(".also", sec_files1.getPattern());
+    Assert.assertEquals(true, sec_files1.getRequired());
+    WorkflowInputParameter wf_file_input_array = (WorkflowInputParameter) inputs.get(2);
+    Assert.assertEquals(workflow_id + "/wf_file_input_array", wf_file_input_array.getId().get());
+    List<SecondaryFileSchema> sec_files_l2 = (List<SecondaryFileSchema>) wf_file_input_array.getSecondaryFiles();
+    Assert.assertEquals(1,  sec_files_l2.size());
+    SecondaryFileSchema sec_files2 = sec_files_l2.get(0);
+    Assert.assertEquals(".also", sec_files2.getPattern());
+    Assert.assertEquals(true,  sec_files2.getRequired());
```
Comment (mr-c) [inline src/test/java/org/w3id/cwl/cwl1_2/utils/SecondaryFilesTest.java:44]: Verification that not only did the file load, the `secondaryFiles` attributes have the expected contents
